const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const SET_COLOR = 'SET_COLOR';
const SET_COMPLETED_STATUS = 'SET_COMPLETED_STATUS';
const SET_ACTIVE_STATUS = 'SET_ACTIVE_STATUS';
const MARK_ALL_COMPLETED = 'MARK_ALL_COMPLETED';
const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export {ADD_TODO , DELETE_TODO , SET_COLOR , SET_COMPLETED_STATUS , SET_ACTIVE_STATUS , MARK_ALL_COMPLETED , CLEAR_COMPLETED}